// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"seas/internal/biz"
	"seas/internal/conf"
	"seas/internal/data"
	"seas/internal/server"
	"seas/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, llm *conf.LLM, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	subjectRepo := data.NewSubjectRepo(dataData)
	scoreRepo := data.NewScoreRepo(dataData, subjectRepo)
	analysisUseCase := biz.NewAnalysisUseCase(scoreRepo, llm)
	examRepo := data.NewExamRepo(dataData)
	examAnalysisUseCase := biz.NewExamAnalysisUseCase(examRepo, subjectRepo, scoreRepo)
	scoreItemRepo := data.NewScoreItemRepo(dataData)
	examAnalysisUseCase = examAnalysisUseCase.WithScoreItemRepo(scoreItemRepo)
	analysisService := service.NewAnalysisService(analysisUseCase, examAnalysisUseCase)
	tracerProvider := NewTraceProvider()
	grpcServer := server.NewGRPCServer(confServer, analysisService, tracerProvider, logger)
	aiAnalysisHandler := server.NewAIAnalysisHandler(analysisService, llm, logger)
	httpServer := server.NewHTTPServer(confServer, analysisService, aiAnalysisHandler, tracerProvider, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
