// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: seas/v1/analysis.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StudentNlInput string                 `protobuf:"bytes,1,opt,name=student_nl_input,json=studentNlInput,proto3" json:"student_nl_input,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_seas_v1_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seas_v1_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_seas_v1_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetStudentNlInput() string {
	if x != nil {
		return x.StudentNlInput
	}
	return ""
}

type AnalyzeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultSummary string                 `protobuf:"bytes,1,opt,name=result_summary,json=resultSummary,proto3" json:"result_summary,omitempty"`
	Suggestions   []string               `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeReply) Reset() {
	*x = AnalyzeReply{}
	mi := &file_seas_v1_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeReply) ProtoMessage() {}

func (x *AnalyzeReply) ProtoReflect() protoreflect.Message {
	mi := &file_seas_v1_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeReply.ProtoReflect.Descriptor instead.
func (*AnalyzeReply) Descriptor() ([]byte, []int) {
	return file_seas_v1_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeReply) GetResultSummary() string {
	if x != nil {
		return x.ResultSummary
	}
	return ""
}

func (x *AnalyzeReply) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_seas_v1_analysis_proto protoreflect.FileDescriptor

const file_seas_v1_analysis_proto_rawDesc = "" +
	"\n" +
	"\x16seas/v1/analysis.proto\x12\aseas.v1\x1a\x1cgoogle/api/annotations.proto\":\n" +
	"\x0eAnalyzeRequest\x12(\n" +
	"\x10student_nl_input\x18\x01 \x01(\tR\x0estudentNlInput\"W\n" +
	"\fAnalyzeReply\x12%\n" +
	"\x0eresult_summary\x18\x01 \x01(\tR\rresultSummary\x12 \n" +
	"\vsuggestions\x18\x02 \x03(\tR\vsuggestions2o\n" +
	"\bAnalysis\x12c\n" +
	"\aAnalyze\x12\x17.seas.v1.AnalyzeRequest\x1a\x15.seas.v1.AnalyzeReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/seas/api/v1/analysis/analyzeB7\n" +
	"\x16dev.kratos.api.seas.v1B\vseasProtoV1P\x01Z\x0eapi/seas/v1;v1b\x06proto3"

var (
	file_seas_v1_analysis_proto_rawDescOnce sync.Once
	file_seas_v1_analysis_proto_rawDescData []byte
)

func file_seas_v1_analysis_proto_rawDescGZIP() []byte {
	file_seas_v1_analysis_proto_rawDescOnce.Do(func() {
		file_seas_v1_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seas_v1_analysis_proto_rawDesc), len(file_seas_v1_analysis_proto_rawDesc)))
	})
	return file_seas_v1_analysis_proto_rawDescData
}

var file_seas_v1_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_seas_v1_analysis_proto_goTypes = []any{
	(*AnalyzeRequest)(nil), // 0: seas.v1.AnalyzeRequest
	(*AnalyzeReply)(nil),   // 1: seas.v1.AnalyzeReply
}
var file_seas_v1_analysis_proto_depIdxs = []int32{
	0, // 0: seas.v1.Analysis.Analyze:input_type -> seas.v1.AnalyzeRequest
	1, // 1: seas.v1.Analysis.Analyze:output_type -> seas.v1.AnalyzeReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seas_v1_analysis_proto_init() }
func file_seas_v1_analysis_proto_init() {
	if File_seas_v1_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seas_v1_analysis_proto_rawDesc), len(file_seas_v1_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seas_v1_analysis_proto_goTypes,
		DependencyIndexes: file_seas_v1_analysis_proto_depIdxs,
		MessageInfos:      file_seas_v1_analysis_proto_msgTypes,
	}.Build()
	File_seas_v1_analysis_proto = out.File
	file_seas_v1_analysis_proto_goTypes = nil
	file_seas_v1_analysis_proto_depIdxs = nil
}
