// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: seas/v1/analysis.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAnalysisGetClassSubjectSummary = "/seas.v1.Analysis/GetClassSubjectSummary"
const OperationAnalysisGetClassSummary = "/seas.v1.Analysis/GetClassSummary"
const OperationAnalysisGetRatingDistribution = "/seas.v1.Analysis/GetRatingDistribution"
const OperationAnalysisGetSingleClassQuestions = "/seas.v1.Analysis/GetSingleClassQuestions"
const OperationAnalysisGetSingleClassSummary = "/seas.v1.Analysis/GetSingleClassSummary"
const OperationAnalysisGetSingleQuestionDetail = "/seas.v1.Analysis/GetSingleQuestionDetail"
const OperationAnalysisGetSingleQuestionSummary = "/seas.v1.Analysis/GetSingleQuestionSummary"
const OperationAnalysisGetSubjectSummary = "/seas.v1.Analysis/GetSubjectSummary"
const OperationAnalysisListExams = "/seas.v1.Analysis/ListExams"
const OperationAnalysisListSubjectsByExam = "/seas.v1.Analysis/ListSubjectsByExam"

type AnalysisHTTPServer interface {
	// GetClassSubjectSummary 新增接口：班级学科下钻
	GetClassSubjectSummary(context.Context, *GetClassSubjectSummaryRequest) (*GetClassSubjectSummaryReply, error)
	// GetClassSummary 新增接口：班级情况汇总
	GetClassSummary(context.Context, *GetClassSummaryRequest) (*GetClassSummaryReply, error)
	// GetRatingDistribution 新增接口：四率分析
	GetRatingDistribution(context.Context, *GetRatingDistributionRequest) (*GetRatingDistributionReply, error)
	// GetSingleClassQuestions 新增接口：单科班级题目汇总
	GetSingleClassQuestions(context.Context, *GetSingleClassQuestionsRequest) (*GetSingleClassQuestionsReply, error)
	// GetSingleClassSummary 新增接口：单科班级汇总
	GetSingleClassSummary(context.Context, *GetSingleClassSummaryRequest) (*GetSingleClassSummaryReply, error)
	// GetSingleQuestionDetail 新增接口：单科班级题目详情
	GetSingleQuestionDetail(context.Context, *GetSingleQuestionDetailRequest) (*GetSingleQuestionDetailReply, error)
	// GetSingleQuestionSummary 新增接口：单科题目汇总
	GetSingleQuestionSummary(context.Context, *GetSingleQuestionSummaryRequest) (*GetSingleQuestionSummaryReply, error)
	// GetSubjectSummary 新增接口：学科情况汇总
	GetSubjectSummary(context.Context, *GetSubjectSummaryRequest) (*GetSubjectSummaryReply, error)
	// ListExams 新增接口：考试列表
	ListExams(context.Context, *ListExamsRequest) (*ListExamsReply, error)
	// ListSubjectsByExam 新增接口：获取考试关联的学科列表
	ListSubjectsByExam(context.Context, *ListSubjectsByExamRequest) (*ListSubjectsByExamReply, error)
}

func RegisterAnalysisHTTPServer(s *http.Server, srv AnalysisHTTPServer) {
	r := s.Route("/")
	r.GET("/seas/api/v1/exams", _Analysis_ListExams0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/subjects", _Analysis_ListSubjectsByExam0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/analysis/subject-summary", _Analysis_GetSubjectSummary0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/analysis/class-summary", _Analysis_GetClassSummary0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/classes/{class_id}/subjects", _Analysis_GetClassSubjectSummary0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/subjects/{subject_id}/classes", _Analysis_GetSingleClassSummary0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/subjects/{subject_id}/classes/{class_id}/questions", _Analysis_GetSingleClassQuestions0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/subjects/{subject_id}/questions", _Analysis_GetSingleQuestionSummary0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/subjects/{subject_id}/classes/{class_id}/questions/{question_id}", _Analysis_GetSingleQuestionDetail0_HTTP_Handler(srv))
	r.GET("/seas/api/v1/exams/{exam_id}/analysis/rating-distribution", _Analysis_GetRatingDistribution0_HTTP_Handler(srv))
}

func _Analysis_ListExams0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListExamsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisListExams)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListExams(ctx, req.(*ListExamsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListExamsReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_ListSubjectsByExam0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSubjectsByExamRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisListSubjectsByExam)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSubjectsByExam(ctx, req.(*ListSubjectsByExamRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSubjectsByExamReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_GetSubjectSummary0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSubjectSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisGetSubjectSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSubjectSummary(ctx, req.(*GetSubjectSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSubjectSummaryReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_GetClassSummary0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetClassSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisGetClassSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetClassSummary(ctx, req.(*GetClassSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetClassSummaryReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_GetClassSubjectSummary0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetClassSubjectSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisGetClassSubjectSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetClassSubjectSummary(ctx, req.(*GetClassSubjectSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetClassSubjectSummaryReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_GetSingleClassSummary0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSingleClassSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisGetSingleClassSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSingleClassSummary(ctx, req.(*GetSingleClassSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSingleClassSummaryReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_GetSingleClassQuestions0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSingleClassQuestionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisGetSingleClassQuestions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSingleClassQuestions(ctx, req.(*GetSingleClassQuestionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSingleClassQuestionsReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_GetSingleQuestionSummary0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSingleQuestionSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisGetSingleQuestionSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSingleQuestionSummary(ctx, req.(*GetSingleQuestionSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSingleQuestionSummaryReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_GetSingleQuestionDetail0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSingleQuestionDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisGetSingleQuestionDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSingleQuestionDetail(ctx, req.(*GetSingleQuestionDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSingleQuestionDetailReply)
		return ctx.Result(200, reply)
	}
}

func _Analysis_GetRatingDistribution0_HTTP_Handler(srv AnalysisHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRatingDistributionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisGetRatingDistribution)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRatingDistribution(ctx, req.(*GetRatingDistributionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRatingDistributionReply)
		return ctx.Result(200, reply)
	}
}

type AnalysisHTTPClient interface {
	GetClassSubjectSummary(ctx context.Context, req *GetClassSubjectSummaryRequest, opts ...http.CallOption) (rsp *GetClassSubjectSummaryReply, err error)
	GetClassSummary(ctx context.Context, req *GetClassSummaryRequest, opts ...http.CallOption) (rsp *GetClassSummaryReply, err error)
	GetRatingDistribution(ctx context.Context, req *GetRatingDistributionRequest, opts ...http.CallOption) (rsp *GetRatingDistributionReply, err error)
	GetSingleClassQuestions(ctx context.Context, req *GetSingleClassQuestionsRequest, opts ...http.CallOption) (rsp *GetSingleClassQuestionsReply, err error)
	GetSingleClassSummary(ctx context.Context, req *GetSingleClassSummaryRequest, opts ...http.CallOption) (rsp *GetSingleClassSummaryReply, err error)
	GetSingleQuestionDetail(ctx context.Context, req *GetSingleQuestionDetailRequest, opts ...http.CallOption) (rsp *GetSingleQuestionDetailReply, err error)
	GetSingleQuestionSummary(ctx context.Context, req *GetSingleQuestionSummaryRequest, opts ...http.CallOption) (rsp *GetSingleQuestionSummaryReply, err error)
	GetSubjectSummary(ctx context.Context, req *GetSubjectSummaryRequest, opts ...http.CallOption) (rsp *GetSubjectSummaryReply, err error)
	ListExams(ctx context.Context, req *ListExamsRequest, opts ...http.CallOption) (rsp *ListExamsReply, err error)
	ListSubjectsByExam(ctx context.Context, req *ListSubjectsByExamRequest, opts ...http.CallOption) (rsp *ListSubjectsByExamReply, err error)
}

type AnalysisHTTPClientImpl struct {
	cc *http.Client
}

func NewAnalysisHTTPClient(client *http.Client) AnalysisHTTPClient {
	return &AnalysisHTTPClientImpl{client}
}

func (c *AnalysisHTTPClientImpl) GetClassSubjectSummary(ctx context.Context, in *GetClassSubjectSummaryRequest, opts ...http.CallOption) (*GetClassSubjectSummaryReply, error) {
	var out GetClassSubjectSummaryReply
	pattern := "/seas/api/v1/exams/{exam_id}/classes/{class_id}/subjects"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisGetClassSubjectSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) GetClassSummary(ctx context.Context, in *GetClassSummaryRequest, opts ...http.CallOption) (*GetClassSummaryReply, error) {
	var out GetClassSummaryReply
	pattern := "/seas/api/v1/exams/{exam_id}/analysis/class-summary"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisGetClassSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) GetRatingDistribution(ctx context.Context, in *GetRatingDistributionRequest, opts ...http.CallOption) (*GetRatingDistributionReply, error) {
	var out GetRatingDistributionReply
	pattern := "/seas/api/v1/exams/{exam_id}/analysis/rating-distribution"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisGetRatingDistribution))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) GetSingleClassQuestions(ctx context.Context, in *GetSingleClassQuestionsRequest, opts ...http.CallOption) (*GetSingleClassQuestionsReply, error) {
	var out GetSingleClassQuestionsReply
	pattern := "/seas/api/v1/exams/{exam_id}/subjects/{subject_id}/classes/{class_id}/questions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisGetSingleClassQuestions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) GetSingleClassSummary(ctx context.Context, in *GetSingleClassSummaryRequest, opts ...http.CallOption) (*GetSingleClassSummaryReply, error) {
	var out GetSingleClassSummaryReply
	pattern := "/seas/api/v1/exams/{exam_id}/subjects/{subject_id}/classes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisGetSingleClassSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) GetSingleQuestionDetail(ctx context.Context, in *GetSingleQuestionDetailRequest, opts ...http.CallOption) (*GetSingleQuestionDetailReply, error) {
	var out GetSingleQuestionDetailReply
	pattern := "/seas/api/v1/exams/{exam_id}/subjects/{subject_id}/classes/{class_id}/questions/{question_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisGetSingleQuestionDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) GetSingleQuestionSummary(ctx context.Context, in *GetSingleQuestionSummaryRequest, opts ...http.CallOption) (*GetSingleQuestionSummaryReply, error) {
	var out GetSingleQuestionSummaryReply
	pattern := "/seas/api/v1/exams/{exam_id}/subjects/{subject_id}/questions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisGetSingleQuestionSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) GetSubjectSummary(ctx context.Context, in *GetSubjectSummaryRequest, opts ...http.CallOption) (*GetSubjectSummaryReply, error) {
	var out GetSubjectSummaryReply
	pattern := "/seas/api/v1/exams/{exam_id}/analysis/subject-summary"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisGetSubjectSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) ListExams(ctx context.Context, in *ListExamsRequest, opts ...http.CallOption) (*ListExamsReply, error) {
	var out ListExamsReply
	pattern := "/seas/api/v1/exams"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisListExams))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisHTTPClientImpl) ListSubjectsByExam(ctx context.Context, in *ListSubjectsByExamRequest, opts ...http.CallOption) (*ListSubjectsByExamReply, error) {
	var out ListSubjectsByExamReply
	pattern := "/seas/api/v1/exams/{exam_id}/subjects"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisListSubjectsByExam))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
