// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/seas/v1/auth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestRequest) Reset() {
	*x = LoginRequestRequest{}
	mi := &file_api_seas_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestRequest) ProtoMessage() {}

func (x *LoginRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_seas_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestRequest.ProtoReflect.Descriptor instead.
func (*LoginRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_seas_v1_auth_proto_rawDescGZIP(), []int{0}
}

type LoginRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	QrUrl         string                 `protobuf:"bytes,2,opt,name=qr_url,json=qrUrl,proto3" json:"qr_url,omitempty"`
	ExpireSeconds int32                  `protobuf:"varint,3,opt,name=expire_seconds,json=expireSeconds,proto3" json:"expire_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestResponse) Reset() {
	*x = LoginRequestResponse{}
	mi := &file_api_seas_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestResponse) ProtoMessage() {}

func (x *LoginRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_seas_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestResponse.ProtoReflect.Descriptor instead.
func (*LoginRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_seas_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequestResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginRequestResponse) GetQrUrl() string {
	if x != nil {
		return x.QrUrl
	}
	return ""
}

func (x *LoginRequestResponse) GetExpireSeconds() int32 {
	if x != nil {
		return x.ExpireSeconds
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_seas_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_seas_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_seas_v1_auth_proto_rawDescGZIP(), []int{2}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_api_seas_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_seas_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_api_seas_v1_auth_proto_rawDescGZIP(), []int{3}
}

var File_api_seas_v1_auth_proto protoreflect.FileDescriptor

const file_api_seas_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x16api/seas/v1/auth.proto\x12\aseas.v1\x1a\x1cgoogle/api/annotations.proto\"\x15\n" +
	"\x13LoginRequestRequest\"h\n" +
	"\x14LoginRequestResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x15\n" +
	"\x06qr_url\x18\x02 \x01(\tR\x05qrUrl\x12%\n" +
	"\x0eexpire_seconds\x18\x03 \x01(\x05R\rexpireSeconds\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse2\xdf\x01\n" +
	"\x04Auth\x12w\n" +
	"\fLoginRequest\x12\x1c.seas.v1.LoginRequestRequest\x1a\x1d.seas.v1.LoginRequestResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/seas/api/v1/auth/login-request\x12^\n" +
	"\x06Logout\x12\x16.seas.v1.LogoutRequest\x1a\x17.seas.v1.LogoutResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/seas/api/v1/auth/logoutB\x10Z\x0eapi/seas/v1;v1b\x06proto3"

var (
	file_api_seas_v1_auth_proto_rawDescOnce sync.Once
	file_api_seas_v1_auth_proto_rawDescData []byte
)

func file_api_seas_v1_auth_proto_rawDescGZIP() []byte {
	file_api_seas_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_seas_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_seas_v1_auth_proto_rawDesc), len(file_api_seas_v1_auth_proto_rawDesc)))
	})
	return file_api_seas_v1_auth_proto_rawDescData
}

var file_api_seas_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_seas_v1_auth_proto_goTypes = []any{
	(*LoginRequestRequest)(nil),  // 0: seas.v1.LoginRequestRequest
	(*LoginRequestResponse)(nil), // 1: seas.v1.LoginRequestResponse
	(*LogoutRequest)(nil),        // 2: seas.v1.LogoutRequest
	(*LogoutResponse)(nil),       // 3: seas.v1.LogoutResponse
}
var file_api_seas_v1_auth_proto_depIdxs = []int32{
	0, // 0: seas.v1.Auth.LoginRequest:input_type -> seas.v1.LoginRequestRequest
	2, // 1: seas.v1.Auth.Logout:input_type -> seas.v1.LogoutRequest
	1, // 2: seas.v1.Auth.LoginRequest:output_type -> seas.v1.LoginRequestResponse
	3, // 3: seas.v1.Auth.Logout:output_type -> seas.v1.LogoutResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_seas_v1_auth_proto_init() }
func file_api_seas_v1_auth_proto_init() {
	if File_api_seas_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_seas_v1_auth_proto_rawDesc), len(file_api_seas_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_seas_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_seas_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_seas_v1_auth_proto_msgTypes,
	}.Build()
	File_api_seas_v1_auth_proto = out.File
	file_api_seas_v1_auth_proto_goTypes = nil
	file_api_seas_v1_auth_proto_depIdxs = nil
}
