// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: seas/v1/exam_import.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExamImport_CreateExam_FullMethodName              = "/seas.v1.ExamImport/CreateExam"
	ExamImport_ImportScores_FullMethodName            = "/seas.v1.ExamImport/ImportScores"
	ExamImport_UpdateSubjectFullScores_FullMethodName = "/seas.v1.ExamImport/UpdateSubjectFullScores"
)

// ExamImportClient is the client API for ExamImport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExamImportClient interface {
	// 创建考试（不含成绩数据，仅创建考试记录）
	CreateExam(ctx context.Context, in *CreateExamRequest, opts ...grpc.CallOption) (*CreateExamReply, error)
	// 导入成绩（multipart/form-data 上传 Excel）
	ImportScores(ctx context.Context, in *ImportScoresRequest, opts ...grpc.CallOption) (*ImportScoresReply, error)
	// 更新考试各学科满分
	UpdateSubjectFullScores(ctx context.Context, in *UpdateSubjectFullScoresRequest, opts ...grpc.CallOption) (*UpdateSubjectFullScoresReply, error)
}

type examImportClient struct {
	cc grpc.ClientConnInterface
}

func NewExamImportClient(cc grpc.ClientConnInterface) ExamImportClient {
	return &examImportClient{cc}
}

func (c *examImportClient) CreateExam(ctx context.Context, in *CreateExamRequest, opts ...grpc.CallOption) (*CreateExamReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExamReply)
	err := c.cc.Invoke(ctx, ExamImport_CreateExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examImportClient) ImportScores(ctx context.Context, in *ImportScoresRequest, opts ...grpc.CallOption) (*ImportScoresReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportScoresReply)
	err := c.cc.Invoke(ctx, ExamImport_ImportScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examImportClient) UpdateSubjectFullScores(ctx context.Context, in *UpdateSubjectFullScoresRequest, opts ...grpc.CallOption) (*UpdateSubjectFullScoresReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubjectFullScoresReply)
	err := c.cc.Invoke(ctx, ExamImport_UpdateSubjectFullScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamImportServer is the server API for ExamImport service.
// All implementations must embed UnimplementedExamImportServer
// for forward compatibility.
type ExamImportServer interface {
	// 创建考试（不含成绩数据，仅创建考试记录）
	CreateExam(context.Context, *CreateExamRequest) (*CreateExamReply, error)
	// 导入成绩（multipart/form-data 上传 Excel）
	ImportScores(context.Context, *ImportScoresRequest) (*ImportScoresReply, error)
	// 更新考试各学科满分
	UpdateSubjectFullScores(context.Context, *UpdateSubjectFullScoresRequest) (*UpdateSubjectFullScoresReply, error)
	mustEmbedUnimplementedExamImportServer()
}

// UnimplementedExamImportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExamImportServer struct{}

func (UnimplementedExamImportServer) CreateExam(context.Context, *CreateExamRequest) (*CreateExamReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExam not implemented")
}
func (UnimplementedExamImportServer) ImportScores(context.Context, *ImportScoresRequest) (*ImportScoresReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportScores not implemented")
}
func (UnimplementedExamImportServer) UpdateSubjectFullScores(context.Context, *UpdateSubjectFullScoresRequest) (*UpdateSubjectFullScoresReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSubjectFullScores not implemented")
}
func (UnimplementedExamImportServer) mustEmbedUnimplementedExamImportServer() {}
func (UnimplementedExamImportServer) testEmbeddedByValue()                    {}

// UnsafeExamImportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamImportServer will
// result in compilation errors.
type UnsafeExamImportServer interface {
	mustEmbedUnimplementedExamImportServer()
}

func RegisterExamImportServer(s grpc.ServiceRegistrar, srv ExamImportServer) {
	// If the following call pancis, it indicates UnimplementedExamImportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExamImport_ServiceDesc, srv)
}

func _ExamImport_CreateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamImportServer).CreateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamImport_CreateExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamImportServer).CreateExam(ctx, req.(*CreateExamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamImport_ImportScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamImportServer).ImportScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamImport_ImportScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamImportServer).ImportScores(ctx, req.(*ImportScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExamImport_UpdateSubjectFullScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubjectFullScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamImportServer).UpdateSubjectFullScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExamImport_UpdateSubjectFullScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamImportServer).UpdateSubjectFullScores(ctx, req.(*UpdateSubjectFullScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExamImport_ServiceDesc is the grpc.ServiceDesc for ExamImport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExamImport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seas.v1.ExamImport",
	HandlerType: (*ExamImportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExam",
			Handler:    _ExamImport_CreateExam_Handler,
		},
		{
			MethodName: "ImportScores",
			Handler:    _ExamImport_ImportScores_Handler,
		},
		{
			MethodName: "UpdateSubjectFullScores",
			Handler:    _ExamImport_UpdateSubjectFullScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seas/v1/exam_import.proto",
}
