// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: seas/v1/exam_import.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // 考试名称，如"2025年春季期中考试"
	ExamDate      string                 `protobuf:"bytes,2,opt,name=exam_date,json=examDate,proto3" json:"exam_date,omitempty"` // 考试时间，RFC3339格式，如"2025-04-15"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExamRequest) Reset() {
	*x = CreateExamRequest{}
	mi := &file_seas_v1_exam_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExamRequest) ProtoMessage() {}

func (x *CreateExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seas_v1_exam_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExamRequest.ProtoReflect.Descriptor instead.
func (*CreateExamRequest) Descriptor() ([]byte, []int) {
	return file_seas_v1_exam_import_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExamRequest) GetExamDate() string {
	if x != nil {
		return x.ExamDate
	}
	return ""
}

type CreateExamReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        string                 `protobuf:"bytes,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"` // 创建的考试ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExamDate      string                 `protobuf:"bytes,3,opt,name=exam_date,json=examDate,proto3" json:"exam_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExamReply) Reset() {
	*x = CreateExamReply{}
	mi := &file_seas_v1_exam_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExamReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExamReply) ProtoMessage() {}

func (x *CreateExamReply) ProtoReflect() protoreflect.Message {
	mi := &file_seas_v1_exam_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExamReply.ProtoReflect.Descriptor instead.
func (*CreateExamReply) Descriptor() ([]byte, []int) {
	return file_seas_v1_exam_import_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExamReply) GetExamId() string {
	if x != nil {
		return x.ExamId
	}
	return ""
}

func (x *CreateExamReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExamReply) GetExamDate() string {
	if x != nil {
		return x.ExamDate
	}
	return ""
}

type ImportScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        string                 `protobuf:"bytes,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"` // 考试ID（URL path参数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportScoresRequest) Reset() {
	*x = ImportScoresRequest{}
	mi := &file_seas_v1_exam_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportScoresRequest) ProtoMessage() {}

func (x *ImportScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seas_v1_exam_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportScoresRequest.ProtoReflect.Descriptor instead.
func (*ImportScoresRequest) Descriptor() ([]byte, []int) {
	return file_seas_v1_exam_import_proto_rawDescGZIP(), []int{2}
}

func (x *ImportScoresRequest) GetExamId() string {
	if x != nil {
		return x.ExamId
	}
	return ""
}

type ImportScoresReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExamId           string                 `protobuf:"bytes,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	ImportedStudents int32                  `protobuf:"varint,2,opt,name=imported_students,json=importedStudents,proto3" json:"imported_students,omitempty"` // 导入学生数
	ImportedSubjects int32                  `protobuf:"varint,3,opt,name=imported_subjects,json=importedSubjects,proto3" json:"imported_subjects,omitempty"` // 导入学科数
	Mode             string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`                                                  // "simple" 或 "full"
	Warnings         []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`                                          // 警告信息列表
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImportScoresReply) Reset() {
	*x = ImportScoresReply{}
	mi := &file_seas_v1_exam_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportScoresReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportScoresReply) ProtoMessage() {}

func (x *ImportScoresReply) ProtoReflect() protoreflect.Message {
	mi := &file_seas_v1_exam_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportScoresReply.ProtoReflect.Descriptor instead.
func (*ImportScoresReply) Descriptor() ([]byte, []int) {
	return file_seas_v1_exam_import_proto_rawDescGZIP(), []int{3}
}

func (x *ImportScoresReply) GetExamId() string {
	if x != nil {
		return x.ExamId
	}
	return ""
}

func (x *ImportScoresReply) GetImportedStudents() int32 {
	if x != nil {
		return x.ImportedStudents
	}
	return 0
}

func (x *ImportScoresReply) GetImportedSubjects() int32 {
	if x != nil {
		return x.ImportedSubjects
	}
	return 0
}

func (x *ImportScoresReply) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ImportScoresReply) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_seas_v1_exam_import_proto protoreflect.FileDescriptor

const file_seas_v1_exam_import_proto_rawDesc = "" +
	"\n" +
	"\x19seas/v1/exam_import.proto\x12\aseas.v1\x1a\x1cgoogle/api/annotations.proto\"D\n" +
	"\x11CreateExamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\texam_date\x18\x02 \x01(\tR\bexamDate\"[\n" +
	"\x0fCreateExamReply\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\tR\x06examId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\texam_date\x18\x03 \x01(\tR\bexamDate\".\n" +
	"\x13ImportScoresRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\tR\x06examId\"\xb6\x01\n" +
	"\x11ImportScoresReply\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\tR\x06examId\x12+\n" +
	"\x11imported_students\x18\x02 \x01(\x05R\x10importedStudents\x12+\n" +
	"\x11imported_subjects\x18\x03 \x01(\x05R\x10importedSubjects\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings2\xf0\x01\n" +
	"\n" +
	"ExamImport\x12a\n" +
	"\n" +
	"CreateExam\x12\x1a.seas.v1.CreateExamRequest\x1a\x18.seas.v1.CreateExamReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/seas/api/v1/exams\x12\x7f\n" +
	"\fImportScores\x12\x1c.seas.v1.ImportScoresRequest\x1a\x1a.seas.v1.ImportScoresReply\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/seas/api/v1/exams/{exam_id}/scores/importB7\n" +
	"\x16dev.kratos.api.seas.v1B\vseasProtoV1P\x01Z\x0eapi/seas/v1;v1b\x06proto3"

var (
	file_seas_v1_exam_import_proto_rawDescOnce sync.Once
	file_seas_v1_exam_import_proto_rawDescData []byte
)

func file_seas_v1_exam_import_proto_rawDescGZIP() []byte {
	file_seas_v1_exam_import_proto_rawDescOnce.Do(func() {
		file_seas_v1_exam_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seas_v1_exam_import_proto_rawDesc), len(file_seas_v1_exam_import_proto_rawDesc)))
	})
	return file_seas_v1_exam_import_proto_rawDescData
}

var file_seas_v1_exam_import_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_seas_v1_exam_import_proto_goTypes = []any{
	(*CreateExamRequest)(nil),   // 0: seas.v1.CreateExamRequest
	(*CreateExamReply)(nil),     // 1: seas.v1.CreateExamReply
	(*ImportScoresRequest)(nil), // 2: seas.v1.ImportScoresRequest
	(*ImportScoresReply)(nil),   // 3: seas.v1.ImportScoresReply
}
var file_seas_v1_exam_import_proto_depIdxs = []int32{
	0, // 0: seas.v1.ExamImport.CreateExam:input_type -> seas.v1.CreateExamRequest
	2, // 1: seas.v1.ExamImport.ImportScores:input_type -> seas.v1.ImportScoresRequest
	1, // 2: seas.v1.ExamImport.CreateExam:output_type -> seas.v1.CreateExamReply
	3, // 3: seas.v1.ExamImport.ImportScores:output_type -> seas.v1.ImportScoresReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seas_v1_exam_import_proto_init() }
func file_seas_v1_exam_import_proto_init() {
	if File_seas_v1_exam_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seas_v1_exam_import_proto_rawDesc), len(file_seas_v1_exam_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seas_v1_exam_import_proto_goTypes,
		DependencyIndexes: file_seas_v1_exam_import_proto_depIdxs,
		MessageInfos:      file_seas_v1_exam_import_proto_msgTypes,
	}.Build()
	File_seas_v1_exam_import_proto = out.File
	file_seas_v1_exam_import_proto_goTypes = nil
	file_seas_v1_exam_import_proto_depIdxs = nil
}
